### ISSUE TITLE
BE: Request Model

### ISSUE THREAD

**Issue by moffatethan** [hatchways/team-teak#9]
The following are properties you may want to consider adding to this model but is not limited to:

\- userId (user who is requesting)
\- sitterId (pet sitter user id)
\- start (date requested to start)
\- end (date requested to end)
\- accepted (default False) 
\- declined (default False)
\- paid (default False)

**Comment by wiroger9595** [comment]
want to make sure does sitterId (pet sitter user id), is reference to userId where table name is user?
